name: Node.js CI

on:
  push:
    branches: [ development, github_workflows ]
  pull_request:
    branches: [ developement ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean install dependencies and build
        run: | 
          npm ci
          npm run build --if-present
        working-directory: ./speaking-portal-project
