name: Node.js CI

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      print_tags:
        description: 'True to print to STDOUT'
        required: true 
        type: boolean 
      tags:
        description: 'Test scenario tags'
        required: true 
        type: string
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
  
jobs:
  build:
    name: node workflow
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [15.x, 19.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Clean install dependencies and build
        run: | 
          npm ci
          npm run build --if-present
        working-directory: ./speaking-portal-project
      - name: Setup FFmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
      - name: Run Jest unit tests
        run: npm test
        working-directory: ./speaking-portal-project
  print-tag:
    runs-on: ubuntu-latest
    if:  ${{ inputs.print_tags }} 
    steps:
      - name: Print the input tag to STDOUT
        run: echo  The tags are ${{ inputs.tags }} 
        
