name: Node.js CI

on:
  push:
    branches: [ development, github_workflows ]
  pull_request:
    branches: [ developement ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
      - name: Clean install dependencies and build
          node-version: '19.x'
        run: | 
          npm ci
          npm run build --if-present
        working-directory: ./speaking-portal-project

